# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [4]:
city_path='/Users/ashwinabraham/Documents/GitHub/python-api-challenge/WeatherPy/cities.csv'
city_df=pd.read_csv(city_path)
city_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Tasiilaq,62,GL,1584069302,66,65.61,-37.64,12.20,23.04
1,Mar del Plata,5,AR,1584069291,94,-38.00,-57.56,72.00,4.70
2,Shatsk,100,RU,1584069451,79,54.03,41.71,43.52,22.93
3,Ponta do Sol,40,PT,1584069301,72,32.67,-17.10,62.60,16.11
4,Bredasdorp,0,ZA,1584069296,93,-34.53,20.04,62.60,4.70

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [5]:
# Store latitude and longitude in locations
gmaps.configure(api_key=g_key)
locations = city_df[["Lat", "Lng"]]
fig = gmaps.figure()
humidity = city_df["Humidity"].astype(float)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations,weights=humidity,  
                                 dissipating=False, max_intensity=10,
                                 point_radius=2)

fig=gmaps.figure()
# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [8]:
narrow_city=pd.DataFrame(city_df, columns = ['City','Country','Cloudiness','Humidity','Max Temp','Wind Speed','Lat','Lng'])
cloudiness= narrow_city['Cloudiness'] < 5
humidity=narrow_city['Humidity'] <= 70
max_temp=(narrow_city['Max Temp'] <= 92) & (narrow_city['Max Temp'] >= 69 )
wind_speed=narrow_city['Wind Speed'] < 8
narrow_city=narrow_city[cloudiness & humidity & max_temp & wind_speed ]
narrow_file = "/Users/ashwinabraham/Documents/GitHub/python-api-challenge/WeatherPy/narrow_cities.csv"
narrow_city.to_csv(f'{narrow_file}',index=False, header=True)
narrow_city

,City,Country,Cloudiness,Humidity,Max Temp,Wind Speed,Lat,Lng
31,La Santisima Trinidad,BO,0,68,79.83,2.28,-14.83,-64.90
69,Bougouni,ML,0,11,74.48,5.37,11.42,-7.48
71,Airai,TL,4,56,79.99,6.31,-8.93,125.41
100,Chāmpua,IN,0,51,79.63,0.76,22.08,85.67
139,Ternate,ID,1,57,86.99,6.76,0.80,127.40
170,Ibirubá,BR,0,49,73.53,3.65,-28.63,-53.09
212,El Sauce,NI,0,64,71.44,5.93,12.89,-86.54
265,Les Cayes,HT,0,70,79.05,7.54,18.20,-73.75
270,Teknāf,BD,0,30,90.73,0.13,20.86,92.31
302,Bajil,YE,3,60,73.53,1.88,15.06,43.29
305,Tezu,IN,0,38,76.77,2.91,27.92,96.17
319,Morondava,MG,0,67,74.91,6.13,-20.28,44.28
333,Paranhos,BR,0,64,81.14,7.16,-23.89,-55.43
377,Ratnagiri,IN,0,69,70.61,6.33,16.98,73.30
381,Tambacounda,SN,0,7,86.00,6.93,13.75,-13.76
413,Pāsighāt,IN,0,47,74.71,1.05,28.07,95.33
431,Atambua,ID,3,68,84.00,5.68,-9.11,124.89
445,Padang,ID,0,59,83.71,1.70,-0.95,100.35
463,Batemans Bay,AU,0,42,75.00,1.99,-35.72,150.18
477,Pathein,MM,0,54,85.14,5.08,16.78,94.73
484,Encruzilhada do Sul,BR,0,50,76.01,2.91,-30.54,-52.52
538,Laguna,US,1,28,71.01,3.36,38.42,-121.42
548,Micheweni,TZ,0,70,84.40,7.52,-4.97,39.83

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [9]:
hotel_df=narrow_city

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}


for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]

    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # assemble url and make API request
    print(f"Retrieving Results for {row['City']}.")
    response = requests.get(base_url, params=params).json()
    # print(json.dumps(response, indent=4, sort_keys=True))
    
    # extract results
    results = response['results']
    
    try:
        print(f"In 5000m radius the closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Data Not found")

Retrieving Results for La Santisima Trinidad.
In 5000m radius the closest hotel is Hotel Piesta.
Retrieving Results for Bougouni.
In 5000m radius the closest hotel is Non Stop.
Retrieving Results for Airai.
In 5000m radius the closest hotel is Juvinal Martin.
Retrieving Results for Chāmpua.
In 5000m radius the closest hotel is ANSARI COTTAGE.
Retrieving Results for Ternate.
In 5000m radius the closest hotel is Grand Dafam Bela Ternate.
Retrieving Results for Ibirubá.
In 5000m radius the closest hotel is Hotel Pitangueira - O melhor serviço pelo menor preço..
Retrieving Results for El Sauce.
In 5000m radius the closest hotel is Hotel Blanco.
Retrieving Results for Les Cayes.
In 5000m radius the closest hotel is Villa Orphee.
Retrieving Results for Teknāf.
In 5000m radius the closest hotel is Magnum Engineering & Construction.
Retrieving Results for Bajil.
In 5000m radius the closest hotel is فندق الصقر السياحي.
Retrieving Results for Tezu.
In 5000m radius the closest hotel is Circuit House.
Retrieving Results for Morondava.
In 5000m radius the closest hotel is La Case Bambou.
Retrieving Results for Paranhos.
In 5000m radius the closest hotel is Hotel América.
Retrieving Results for Ratnagiri.
In 5000m radius the closest hotel is Hotel Landmark.
Retrieving Results for Tambacounda.
Data Not found
Retrieving Results for Pāsighāt.
In 5000m radius the closest hotel is Siang Guest House.
Retrieving Results for Atambua.
In 5000m radius the closest hotel is Pondok Pesantren Al Muhajirin Atambua.
Retrieving Results for Padang.
In 5000m radius the closest hotel is Mercure Padang.
Retrieving Results for Batemans Bay.
In 5000m radius the closest hotel is Coachhouse Marina Resort - Batemans Bay.
Retrieving Results for Pathein.
In 5000m radius the closest hotel is Pathein Hotel.
Retrieving Results for Encruzilhada do Sul.
In 5000m radius the closest hotel is Conceição Palace Hotel.
Retrieving Results for Laguna.
In 5000m radius the closest hotel is Holiday Inn Express & Suites Elk Grove Central - Hwy 99.
Retrieving Results for Micheweni.
Data Not found

In [10]:
hotel_df

,City,Country,Cloudiness,Humidity,Max Temp,Wind Speed,Lat,Lng,Hotel Name
31,La Santisima Trinidad,BO,0,68,79.83,2.28,-14.83,-64.90,Hotel Piesta
69,Bougouni,ML,0,11,74.48,5.37,11.42,-7.48,Non Stop
71,Airai,TL,4,56,79.99,6.31,-8.93,125.41,Juvinal Martin
100,Chāmpua,IN,0,51,79.63,0.76,22.08,85.67,ANSARI COTTAGE
139,Ternate,ID,1,57,86.99,6.76,0.80,127.40,Grand Dafam Bela Ternate
170,Ibirubá,BR,0,49,73.53,3.65,-28.63,-53.09,Hotel Pitangueira - O melhor serviço pelo meno...
212,El Sauce,NI,0,64,71.44,5.93,12.89,-86.54,Hotel Blanco
265,Les Cayes,HT,0,70,79.05,7.54,18.20,-73.75,Villa Orphee
270,Teknāf,BD,0,30,90.73,0.13,20.86,92.31,Magnum Engineering & Construction
302,Bajil,YE,3,60,73.53,1.88,15.06,43.29,فندق الصقر السياحي
305,Tezu,IN,0,38,76.77,2.91,27.92,96.17,Circuit House
319,Morondava,MG,0,67,74.91,6.13,-20.28,44.28,La Case Bambou
333,Paranhos,BR,0,64,81.14,7.16,-23.89,-55.43,Hotel América
377,Ratnagiri,IN,0,69,70.61,6.33,16.98,73.30,Hotel Landmark
381,Tambacounda,SN,0,7,86.00,6.93,13.75,-13.76,NaN
413,Pāsighāt,IN,0,47,74.71,1.05,28.07,95.33,Siang Guest House
431,Atambua,ID,3,68,84.00,5.68,-9.11,124.89,Pondok Pesantren Al Muhajirin Atambua
445,Padang,ID,0,59,83.71,1.70,-0.95,100.35,Mercure Padang
463,Batemans Bay,AU,0,42,75.00,1.99,-35.72,150.18,Coachhouse Marina Resort - Batemans Bay
477,Pathein,MM,0,54,85.14,5.08,16.78,94.73,Pathein Hotel
484,Encruzilhada do Sul,BR,0,50,76.01,2.91,-30.54,-52.52,Conceição Palace Hotel
538,Laguna,US,1,28,71.01,3.36,38.42,-121.42,Holiday Inn Express & Suites Elk Grove Central...
548,Micheweni,TZ,0,70,84.40,7.52,-4.97,39.83,NaN

In [11]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [12]:
# Add marker layer ontop of heat map
# Create hotel symbol layer
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))